### ISSUE TITLE
Doesn't work in URP

### ISSUE THREAD

**Issue by hyouuu** [llamacademy/fade-objects-standard-shader#1]
In my URP project the shaders default to Lit, which is supposed to be the equivalent of Standard Shader and I see all the same properties e.g. _DstBlend - it should be an easy change and would really appreciate it if you could take a look soon!

Ref to the Lit shader: https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/lit-shader.html

**Comment by hyouuu** [comment]
Actually, turning the material's surface type to transparent made this work - thanks!

**Comment by llamacademy** [comment]
> Actually, turning the material's surface type to transparent made this work - thanks!

Thanks for that tip! 
I am planning to make a similar video & repo for URP and HDRP since I understand those work differently. 
I just started working with URP as part of upgrading my 2019 built-in render pipeline project to 2021 URP so I'm sure I'll be learning a lot that I can share
